-- Sinh tự động bởi tools/gen-seed-sql.mjs — đừng sửa tay, sửa src/lib/data/seed/*.json rồi chạy lại.
-- Chạy sau 01-schema.sql. Có thể chạy lại nhiều lần (dùng on conflict do update).

-- ------------------------------ categories ------------------------------
insert into public.categories (slug, name, description, image_url, sort_order) values ('hop-giay', 'Hộp giày', 'Hộp giày carton trắng và nâu, carton 3 lớp sóng E, nắp gập tiết kiệm. Dùng cho giày nam, giày nữ, sneaker và các mặt hàng thời trang cần hộp cứng cáp nhưng gấp gọn được để giảm chi phí lưu kho.', '/assets/images/thumbs/home-img1.png', 1)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, image_url = excluded.image_url, sort_order = excluded.sort_order;
insert into public.categories (slug, name, description, image_url, sort_order) values ('hop-nap-gai', 'Hộp nắp gài', 'Hộp nắp gài carton 3 lớp sóng E, nắp gài tiêu chuẩn hoặc nắp gập kiểu thời trang, có mẫu khoét lỗ xách tay. Phù hợp đóng gói mỹ phẩm, phụ kiện, quà tặng và hàng thương mại điện tử.', '/assets/images/thumbs/home-img2.png', 2)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, image_url = excluded.image_url, sort_order = excluded.sort_order;
insert into public.categories (slug, name, description, image_url, sort_order) values ('thung-cod', 'Thùng COD', 'Thùng carton ship hàng COD, carton 3 lớp sóng B chịu lực, in Flexo 1 màu. Dùng cho mỹ phẩm, phụ kiện thời trang, trang sức và hàng gửi chuyển phát.', '/assets/images/thumbs/home-img3.png', 3)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, image_url = excluded.image_url, sort_order = excluded.sort_order;

-- ------------------------------- services -------------------------------
insert into public.services (slug, name, summary, description, icon, image_url, sort_order) values ('in-offset', 'In offset', 'In 4 màu CMYK chuẩn màu, sắc nét, tối ưu chi phí khi in số lượng lớn. Dùng cho catalogue, brochure, tờ rơi, danh thiếp, lịch Tết, hộp giấy cao cấp.', '<p>In offset là kỹ thuật chủ lực cho các ấn phẩm cần độ chuẩn màu cao và số lượng lớn. Mực được truyền từ bản kẽm qua tấm cao su rồi mới lên giấy, nhờ đó hình ảnh sắc nét, màu ổn định giữa các tờ in trong cùng một lệnh.</p><h3>Ứng dụng</h3><ul><li>Catalogue, brochure, profile công ty</li><li>Tờ rơi, poster, standee giấy</li><li>Danh thiếp (name card) 250–400gsm</li><li>Lịch bloc, lịch treo tường, lịch để bàn, lịch sổ tay</li><li>Hộp giấy bồi Duplex cao cấp, hộp quà tặng</li></ul><h3>Quy cách thường dùng</h3><ul><li>Giấy: Couche, Bristol, Ivory, Duplex, giấy mỹ thuật</li><li>Định lượng phổ biến: 200–350gsm cho bao bì, 210–250gsm cho lịch để bàn</li><li>Gia công: cán màng bóng/mờ, ép kim, phủ UV định hình, bế nổi, dập chìm</li></ul><p>Chi phí bản kẽm được chia đều trên số lượng in, nên đơn càng lớn đơn giá càng giảm. Với đơn nhỏ hoặc cần gấp, chúng tôi tư vấn chuyển sang in kỹ thuật số.</p>', 'ph-bold ph-printer', '/assets/images/thumbs/service-big-image1.png', 1)
  on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, icon = excluded.icon, image_url = excluded.image_url, sort_order = excluded.sort_order;
insert into public.services (slug, name, summary, description, icon, image_url, sort_order) values ('in-flexo', 'In flexo', 'In nổi tốc độ cao trên giấy kraft, carton sóng, màng phim và decal. Mực nhanh khô, phù hợp in logo và nhận diện trên thùng carton, tem nhãn số lượng lớn.', '<p>In Flexo (in nổi) dùng khuôn in bằng photopolymer, cao su hoặc nhựa được khắc bằng ánh sáng UV. Mực Flexo nhanh khô nên in được ở tốc độ cao — đây là lý do kỹ thuật này gần như mặc định cho thùng carton và tem nhãn số lượng lớn.</p><h3>Quy trình 4 bước</h3><ul><li>Chuẩn bị file: thiết kế chuyển sang vector để giữ độ sắc nét</li><li>Làm khuôn in (plate making) bằng ánh sáng UV</li><li>In lên chất liệu bao bì</li><li>Sấy khô, cắt, gấp và hoàn thiện</li></ul><h3>Lưu ý khi thiết kế cho in Flexo</h3><ul><li>Không để chi tiết quá nhỏ hoặc quá phức tạp — dễ mất nét khi in</li><li>Chọn mực phù hợp chất liệu để đảm bảo độ bền màu</li><li>Cân bằng áp lực in để mực không bị lem hoặc thiếu</li><li>Kiểm tra độ dày khuôn và hiệu chỉnh hệ thống kiểm soát màu trước khi chạy sản lượng</li></ul>', 'ph-bold ph-stack', '/assets/images/thumbs/service-big-image2.png', 2)
  on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, icon = excluded.icon, image_url = excluded.image_url, sort_order = excluded.sort_order;
insert into public.services (slug, name, summary, description, icon, image_url, sort_order) values ('thiet-ke-bao-bi', 'Thiết kế bao bì', 'Thiết kế hộp giấy, túi xách giấy, tem nhãn và bộ nhận diện bao bì theo đúng quy cách sản xuất. Miễn phí thiết kế cho đơn in tại xưởng.', '<p>Thiết kế bao bì ở In Ấn Thời Đại luôn đi kèm quy cách sản xuất: dao bế, biên dán, nếp gấp và dung sai đều được tính trước, để bản thiết kế in ra đúng như bản duyệt.</p><h3>Nguyên tắc chúng tôi áp dụng</h3><ul><li>Biên dán tối thiểu 25mm để hộp không bị bung</li><li>Nếp gấp phải được tạo rãnh chuẩn, tránh nứt giấy sau cán màng</li><li>Kích thước hộp dư 0.5–1cm so với sản phẩm để dễ đóng gói</li><li>Logo đặt tránh mép gấp, đảm bảo hiển thị đủ trên mọi mặt</li><li>Không lạm dụng nhiều hiệu ứng cùng lúc — vừa đội chi phí vừa dễ nứt bề mặt</li></ul><h3>Hạng mục thiết kế</h3><ul><li>Hộp giấy, hộp cứng nắp nam châm, hộp ngăn kéo, hộp gấp gọn</li><li>Túi xách giấy: quai giấy xoắn, quai dây dù, quai ruy băng, quai PP dẹt</li><li>Tem nhãn decal: giấy, nhựa trong, kim loại, decal chống nước</li><li>Tag treo: oval, tròn, lục giác, vuông/chữ nhật đứng và ngang</li></ul>', 'ph-bold ph-pen-nib', '/assets/images/thumbs/service-big-image3.png', 3)
  on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, icon = excluded.icon, image_url = excluded.image_url, sort_order = excluded.sort_order;
insert into public.services (slug, name, summary, description, icon, image_url, sort_order) values ('gia-cong-sau-in', 'Gia công sau in', 'Cán màng bóng/mờ, ép kim, phủ UV định hình, bế nổi, dập chìm, bồi giấy, gấp dán tự động. Bước quyết định cảm giác cầm của sản phẩm cuối.', '<p>Gia công sau in là bước khiến hai sản phẩm in giống nhau lại cho cảm giác hoàn toàn khác. Xưởng Thời Đại xử lý trọn gói sau in nên không phải chuyển qua nhiều nơi, rút ngắn thời gian giao hàng.</p><h3>Các hạng mục</h3><ul><li><strong>Cán màng bóng / mờ</strong> — bảo vệ bề mặt, tăng độ bền và cảm giác cầm</li><li><strong>Ép kim</strong> — làm nổi logo, tạo điểm nhấn cao cấp, nhiều màu nhũ</li><li><strong>Phủ UV định hình</strong> — tạo độ bóng cục bộ ở phần muốn nhấn</li><li><strong>Bế nổi / dập chìm</strong> — tạo hiệu ứng chạm, chuyên nghiệp và khác biệt</li><li><strong>Bồi giấy Duplex 250–350gsm</strong> lên carton sóng B, C hoặc BE</li><li><strong>Gấp dán</strong> bằng keo tự động hoặc dán tay tuỳ kết cấu hộp</li></ul><h3>Lưu ý</h3><p>Màu in có thể lệch nhẹ giữa giấy thường và giấy đã cán màng — nên duyệt test proof trên đúng chất liệu trước khi chạy sản lượng.</p>', 'ph-bold ph-sparkle', '/assets/images/thumbs/service-big-image4.png', 4)
  on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, icon = excluded.icon, image_url = excluded.image_url, sort_order = excluded.sort_order;

-- ------------------------------- products -------------------------------
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-giay-trang-carton-29x17x9-5cm', 'Hộp giày trắng Carton 29x17x9.5cm', 'LT009', 'hop-giay', 460000, 2400000, '[{"qty":100,"price":460000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":2400000}]'::jsonb, 'Carton 3 lớp sóng E (N+2X), kích thước 29 x 17 x 9.5 cm, màu trắng hoặc nâu. Nắp gập kiểu tiết kiệm, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp giày trắng Carton 29x17x9.5cm là hộp giày do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e (n+2x), sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gập kiểu tiết kiệm. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E (N+2X)","Kích thước (D x R x C)":"29 x 17 x 9.5 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gập kiểu tiết kiệm","Kỹ thuật in":"In Flexo 1 màu","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img1.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-giay-trang-carton-31x19x11cm', 'Hộp giày trắng Carton 31x19x11cm', 'LT004', 'hop-giay', 630000, 3150000, '[{"qty":100,"price":630000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":3150000}]'::jsonb, 'Carton 3 lớp sóng E (N+2X), kích thước 31 x 19 x 11 cm, màu trắng hoặc nâu. Nắp gập kiểu tiết kiệm, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp giày trắng Carton 31x19x11cm là hộp giày do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e (n+2x), sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gập kiểu tiết kiệm. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E (N+2X)","Kích thước (D x R x C)":"31 x 19 x 11 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gập kiểu tiết kiệm","Kỹ thuật in":"In Flexo 1 màu","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img2.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-giay-trang-carton-32-5x20x11cm', 'Hộp giày trắng Carton 32.5x20x11cm', 'LT0008', 'hop-giay', 555000, 3330000, '[{"qty":100,"price":555000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":3330000}]'::jsonb, 'Carton 3 lớp sóng E (N+2X), kích thước 32.5 x 20 x 11 cm, màu trắng hoặc nâu. Nắp gập kiểu tiết kiệm, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp giày trắng Carton 32.5x20x11cm là hộp giày do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e (n+2x), sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gập kiểu tiết kiệm. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E (N+2X)","Kích thước (D x R x C)":"32.5 x 20 x 11 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gập kiểu tiết kiệm","Kỹ thuật in":"In Flexo 1 màu","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img3.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-giay-trang-carton-32x20x12cm', 'Hộp giày trắng Carton 32x20x12cm', 'LT0010', 'hop-giay', 654000, 3325000, '[{"qty":100,"price":654000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":3325000}]'::jsonb, 'Carton 3 lớp sóng E (N+2X), kích thước 32 x 20 x 12 cm, màu trắng hoặc nâu. Nắp gập kiểu tiết kiệm, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp giày trắng Carton 32x20x12cm là hộp giày do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e (n+2x), sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gập kiểu tiết kiệm. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E (N+2X)","Kích thước (D x R x C)":"32 x 20 x 12 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gập kiểu tiết kiệm","Kỹ thuật in":"In Flexo 1 màu","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img4.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-nap-gai-carton-12x11x9cm', 'Hộp nắp gài Carton 12x11x9cm', null, 'hop-nap-gai', 265000, 1350000, '[{"qty":100,"price":265000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":1350000}]'::jsonb, 'Carton 3 lớp sóng E (2N+X), kích thước 12 x 11 x 9 cm, màu trắng hoặc nâu. Nắp gập kiểu thời trang, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp nắp gài Carton 12x11x9cm là hộp nắp gài do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e (2n+x), sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gập kiểu thời trang. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E (2N+X)","Kích thước (D x R x C)":"12 x 11 x 9 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gập kiểu thời trang","Kỹ thuật in":"Không in sẵn — nhận in theo yêu cầu từ 500 hộp","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img5.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-nap-gai-carton-12-5x9-5x21-4cm', 'Hộp nắp gài Carton 12.5x9.5x21.4cm', null, 'hop-nap-gai', 305000, 1575000, '[{"qty":100,"price":305000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":1575000}]'::jsonb, 'Carton 3 lớp sóng E, kích thước 12.5 x 9.5 x 21.4 cm, màu trắng hoặc nâu. Nắp gài tiêu chuẩn, đáy gài, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp nắp gài Carton 12.5x9.5x21.4cm là hộp nắp gài do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e, sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gài tiêu chuẩn, đáy gài. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E","Kích thước (D x R x C)":"12.5 x 9.5 x 21.4 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gài tiêu chuẩn, đáy gài","Kỹ thuật in":"Không in sẵn — nhận in theo yêu cầu từ 500 hộp","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img6.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], false)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-nap-gai-carton-14-5x10x19-5cm', 'Hộp nắp gài Carton 14.5x10x19.5cm', null, 'hop-nap-gai', 320000, 1625000, '[{"qty":100,"price":320000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":1625000}]'::jsonb, 'Carton 3 lớp sóng E, kích thước 14.5 x 10 x 19.5 cm, màu trắng hoặc nâu. Nắp gài tiêu chuẩn, đáy gài, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp nắp gài Carton 14.5x10x19.5cm là hộp nắp gài do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e, sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gài tiêu chuẩn, đáy gài. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E","Kích thước (D x R x C)":"14.5 x 10 x 19.5 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gài tiêu chuẩn, đáy gài","Kỹ thuật in":"Không in sẵn — nhận in theo yêu cầu từ 500 hộp","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img7.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-nap-gai-carton-15x7-5x26-9cm', 'Hộp nắp gài Carton 15x7.5x26.9cm', null, 'hop-nap-gai', 315000, 1625000, '[{"qty":100,"price":315000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":1625000}]'::jsonb, 'Carton 3 lớp sóng E, kích thước 15 x 7.5 x 26.9 cm, màu trắng hoặc nâu. Nắp gài có khoét lỗ xách tay, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp nắp gài Carton 15x7.5x26.9cm là hộp nắp gài do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e, sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gài có khoét lỗ xách tay. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E","Kích thước (D x R x C)":"15 x 7.5 x 26.9 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gài có khoét lỗ xách tay","Kỹ thuật in":"Không in sẵn — nhận in theo yêu cầu từ 500 hộp","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img8.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], false)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-nap-gai-carton-19-5x6x18-5cm', 'Hộp nắp gài Carton 19.5x6x18.5cm', null, 'hop-nap-gai', 280000, 1450000, '[{"qty":100,"price":280000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":1450000}]'::jsonb, 'Carton 3 lớp sóng E, kích thước 19.5 x 6 x 18.5 cm, màu trắng hoặc nâu. Nắp gài tiêu chuẩn, đáy gài, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp nắp gài Carton 19.5x6x18.5cm là hộp nắp gài do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e, sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gài tiêu chuẩn, đáy gài. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E","Kích thước (D x R x C)":"19.5 x 6 x 18.5 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gài tiêu chuẩn, đáy gài","Kỹ thuật in":"Không in sẵn — nhận in theo yêu cầu từ 500 hộp","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img9.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], false)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-nap-gai-carton-25x25x10cm', 'Hộp nắp gài Carton 25x25x10cm', null, 'hop-nap-gai', 640000, 3150000, '[{"qty":100,"price":640000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":3150000}]'::jsonb, 'Carton 3 lớp sóng E, kích thước 25 x 25 x 10 cm, màu trắng hoặc nâu. Nắp gài tiêu chuẩn, đáy gài, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp nắp gài Carton 25x25x10cm là hộp nắp gài do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e, sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gài tiêu chuẩn, đáy gài. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E","Kích thước (D x R x C)":"25 x 25 x 10 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gài tiêu chuẩn, đáy gài","Kỹ thuật in":"Không in sẵn — nhận in theo yêu cầu từ 500 hộp","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img10.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-nap-gai-carton-27x18x7cm', 'Hộp nắp gài Carton 27x18x7cm', null, 'hop-nap-gai', 480000, 2400000, '[{"qty":100,"price":480000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":2400000}]'::jsonb, 'Carton 3 lớp sóng E (2N+X), kích thước 27 x 18 x 7 cm, màu trắng hoặc nâu. Nắp gập kiểu thời trang, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp nắp gài Carton 27x18x7cm là hộp nắp gài do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng e (2n+x), sóng cao 2mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gập kiểu thời trang. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng E (2N+X)","Kích thước (D x R x C)":"27 x 18 x 7 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"2mm","Kiểu hộp":"Nắp gập kiểu thời trang","Kỹ thuật in":"Không in sẵn — nhận in theo yêu cầu từ 500 hộp","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img11.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], false)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;
insert into public.products (slug, name, sku, category_slug, price_min, price_max, price_tiers, short_description, description, specs, images, is_featured) values ('hop-carton-15x10x20cm', 'Hộp Carton 15x10x20cm', 'LTCOD-007', 'thung-cod', 350000, 1719000, '[{"qty":100,"price":350000},{"qty":200,"price":null},{"qty":300,"price":null},{"qty":400,"price":null},{"qty":500,"price":1719000}]'::jsonb, 'Carton 3 lớp sóng B (2 mặt nâu, 1 lớp sóng), kích thước 15 x 10 x 20 cm, màu trắng hoặc nâu. Nắp gài kiểu tiết kiệm, gấp gọn được để tiết kiệm chi phí lưu kho và vận chuyển.', '<p>Hộp Carton 15x10x20cm là thùng carton COD do Công Ty TNHH Công Nghiệp Thời Đại sản xuất trực tiếp tại xưởng, không qua trung gian. Thùng dùng carton 3 lớp sóng b (2 mặt nâu, 1 lớp sóng), sóng cao 3mm — vừa giữ được độ phẳng và tính thẩm mỹ của bề mặt giấy, vừa chống va đập tốt khi vận chuyển.</p><p>Kiểu hộp: nắp gài kiểu tiết kiệm. Hộp giao ở dạng phôi phẳng, khách tự gấp khi đóng hàng, nhờ đó giảm đáng kể chi phí lưu kho và cước vận chuyển.</p><p>Nhận in logo, nhận diện thương hiệu theo yêu cầu với đơn từ 500 hộp. Đơn trên 500 hộp liên hệ Zalo 0399 466 179 (Ms. Tuyền) để nhận giá ưu đãi. Xưởng nhận sản xuất carton 3 lớp, 5 lớp, 7 lớp với các loại sóng B, C, E theo kích thước riêng của khách.</p>', '{"Chất liệu":"Carton 3 lớp sóng B (2 mặt nâu, 1 lớp sóng)","Kích thước (D x R x C)":"15 x 10 x 20 cm","Màu sắc":"Trắng, nâu","Chiều cao sóng":"3mm","Kiểu hộp":"Nắp gài kiểu tiết kiệm","Kỹ thuật in":"In Flexo 1 màu","Số lượng đặt tối thiểu":"100 hộp","Nhận in theo yêu cầu":"Từ 500 hộp"}'::jsonb, ARRAY['/assets/images/thumbs/shop-img12.png', '/assets/images/thumbs/shop-details-thumb1.png', '/assets/images/thumbs/shop-details-thumb2.png', '/assets/images/thumbs/shop-details-thumb3.png']::text[], true)
  on conflict (slug) do update set name = excluded.name, sku = excluded.sku, category_slug = excluded.category_slug, price_min = excluded.price_min, price_max = excluded.price_max, price_tiers = excluded.price_tiers, short_description = excluded.short_description, description = excluded.description, specs = excluded.specs, images = excluded.images, is_featured = excluded.is_featured;

-- -------------------------------- posts ---------------------------------
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('hop-mat-dong-huong-gia-lai-2026', 'Tham dự chương trình họp mặt đồng hương Gia Lai tại TP.HCM lần 1 – 2026', 'In Ấn Thời Đại tham gia chương trình họp mặt đồng hương Gia Lai lần đầu tiên tổ chức tại TP.HCM, cùng các gian hàng giới thiệu đặc sản và sản phẩm địa phương.', '<p>Công ty In Ấn Thời Đại tham gia sự kiện Họp mặt Đồng hương Gia Lai tại TP.HCM lần đầu tiên năm 2026 — cột mốc đáng nhớ đánh dấu sự gắn kết của những người con phố núi đang sinh sống và làm việc tại miền Nam.</p>
<p>Chương trình quy tụ đông đảo bà con, doanh nhân và sinh viên yêu mến Gia Lai. Đây là dịp để những người con xa quê ôn lại kỷ niệm, chia sẻ câu chuyện lập nghiệp, đồng thời tạo mạng lưới hợp tác và phát triển.</p>
<p>Điểm nhấn nổi bật là các gian hàng giới thiệu đặc sản địa phương, sản phẩm nông nghiệp và dịch vụ do người Gia Lai làm chủ.</p>
<p>In Ấn Thời Đại gửi lời chúc Ban liên lạc đồng hương Gia Lai dồi dào sức khoẻ, thành công và hy vọng tiếp tục đồng hành cùng cộng đồng trong các sự kiện ý nghĩa sắp tới.</p>', 'Hoạt động - Sự kiện', '/assets/images/thumbs/blog-new-img1.png', '2026-03-30', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('tiec-tat-nien-year-end-party-2025', 'Tiệc tất niên — Year End Party 2025 của Công ty In Ấn Thời Đại', 'Ngày 08/02, toàn thể công ty cùng nhìn lại năm 2025 và đặt mục tiêu cho 2026 trong buổi tiệc tất niên ấm áp.', '<p>Ngày 8 tháng 2, Công ty In Ấn – Thiết Kế – Bao Bì Thời Đại tổ chức buổi Tiệc Tất Niên – Year End Party 2025 trong không khí ấm áp, trang trọng và tràn đầy năng lượng tích cực.</p>
<h3>Các hoạt động chính</h3>
<ul><li><strong>Check-in ảnh kỷ niệm</strong> — ghi lại những khoảnh khắc gắn kết của đội ngũ</li>
<li><strong>Tổng kết năm 2025</strong> — ban lãnh đạo cùng nhân viên đánh giá kết quả và định hướng phát triển cho năm 2026</li>
<li><strong>Tiệc tất niên</strong> — toàn thể công ty cùng thưởng thức bữa tiệc cuối năm</li>
<li><strong>Quay số may mắn</strong> — hoạt động phát thưởng với nhiều phần quà hấp dẫn</li></ul>
<p>Sự kiện thể hiện văn hoá doanh nghiệp gắn kết mà công ty hướng đến, chuẩn bị cho những mục tiêu mới và nâng cao chất lượng dịch vụ trong năm 2026.</p>', 'Hoạt động - Sự kiện', '/assets/images/thumbs/blog-new-img2.png', '2026-02-11', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('giao-huu-thien-nguyen-mung-xuan-binh-ngo-2026', 'In Ấn Thời Đại đồng hành cùng trận cầu giao hữu thiện nguyện mừng Xuân Bính Ngọ 2026', 'Trận giao hữu thiện nguyện giữa AE Bình Định FC và Runam Star FC ngày 18/01/2026 tại sân Quân Khu 7, TP.HCM.', '<p>Trận đấu diễn ra lúc 14h00 ngày 18/01/2026 tại Sân bóng Quân Khu 7, Tân Bình, TP.HCM giữa AE Bình Định FC và Runam Star FC. Công ty In Ấn – Thiết Kế – Bao Bì Thời Đại đồng hành cùng trận cầu giao hữu thiện nguyện nhằm lan toả tinh thần thiện nguyện và kết nối cộng đồng.</p>
<p>Sự kiện không chỉ là một trận đấu thể thao mà còn là dịp để cộng đồng doanh nghiệp chung tay đóng góp cho các hoạt động xã hội trong dịp đầu năm mới, với sứ mệnh phát triển thương hiệu song hành cùng trách nhiệm cộng đồng.</p>', 'Hoạt động - Sự kiện', '/assets/images/thumbs/blog-new-img3.png', '2026-01-28', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('mau-thiet-ke-hop-yen-tet-2026', 'Các mẫu thiết kế hộp yến hot — xu hướng hộp yến phong cách Tết 2026', 'Bốn hướng thiết kế hộp yến đang dẫn đầu mùa Tết 2026: truyền thống cao cấp, tối giản hiện đại, hộp nắp nam châm và hộp combo quà tặng.', '<p>Mùa Tết Nguyên Đán 2026 không chỉ là giai đoạn bán hàng cao điểm cho yến sào mà còn là cuộc cạnh tranh về thiết kế bao bì. Trong phân khúc quà biếu sức khoẻ, hộp yến vừa bảo vệ sản phẩm vừa phản ánh giá trị thương hiệu.</p>
<h3>1. Hộp yến phong cách Tết truyền thống cao cấp</h3>
<ul><li>Màu sắc: đỏ đô, vàng ánh kim, xanh ngọc, be cao cấp</li>
<li>Hoạ tiết: hoa mai, hoa đào, chim hạc, trống đồng, mây vân</li>
<li>Gia công: ép kim logo, phủ UV định hình</li>
<li>Phù hợp: yến sào biếu Tết, quà doanh nghiệp, quà tặng đối tác</li></ul>
<h3>2. Thiết kế hiện đại — tối giản sang trọng</h3>
<ul><li>Layout gọn gàng, ít chi tiết nhưng tinh tế</li>
<li>Tông màu trung tính: trắng, kem, xanh than, xám</li>
<li>Nhấn mạnh logo thương hiệu và thông điệp sức khoẻ</li>
<li>Đối tượng: khách hàng trẻ, doanh nhân, quà biếu cao cấp</li></ul>
<h3>3. Hộp yến nắp nam châm — hộp cứng cao cấp</h3>
<p>Kết cấu chắc chắn, bảo vệ yến tốt, cảm giác mở hộp sang trọng và dễ thiết kế khay đựng lọ yến bên trong. Chất liệu: carton lạnh cao cấp, bồi giấy mỹ thuật; gia công ép kim, phủ mờ, dập nổi logo.</p>
<h3>4. Hộp yến kết hợp quà tặng Tết</h3>
<p>Xu hướng mới kết hợp yến với trà thảo mộc, nhân sâm, đông trùng hạ thảo trong hộp đôi, hộp nhiều ngăn, hộp vali hoặc hộp xách tay bồi cứng in offset. Cách làm này tăng giá trị đơn hàng và dễ tiếp cận phân khúc quà biếu doanh nghiệp.</p>', 'Xu hướng thiết kế', '/assets/images/thumbs/blog-img1.png', '2026-01-12', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('cac-loai-tem-nhan-decal-cho-san-pham-tet-2026', 'Các loại tem nhãn decal cho các sản phẩm Tết 2026', 'Decal nhựa trong, decal kim loại, decal giấy hay decal chống nước — chọn loại tem nhãn nào cho từng dòng sản phẩm Tết.', '<p>Tết Nguyên Đán 2026 đang đến gần, là thời điểm các doanh nghiệp hoàn thiện bao bì cho sản phẩm mùa vụ. Tem nhãn decal là chi tiết nhỏ nhưng quyết định phần lớn cảm nhận về chất lượng sản phẩm trên kệ.</p>
<h3>1. Tem nhãn decal nhựa trong suốt</h3>
<p>Phù hợp cho sản phẩm cần thể hiện sự sang trọng: rượu, trà, bánh mứt cao cấp.</p>
<h3>2. Tem nhãn decal kim loại (vàng, bạc)</h3>
<p>Mang vẻ đẹp lấp lánh và sang trọng. Dùng cho trà, cà phê, rượu vang, quà cao cấp.</p>
<h3>3. Tem nhãn decal giấy</h3>
<p>Lựa chọn phổ biến nhất, in được đa dạng màu sắc và thông tin sản phẩm. Dùng cho bánh kẹo, mứt Tết, sản phẩm tiêu dùng.</p>
<h3>4. Tem nhãn decal chống nước</h3>
<p>Bảo vệ thông tin in khỏi mờ hoặc bong tróc. Phù hợp sản phẩm tiếp xúc nước hoặc môi trường ẩm.</p>
<h3>Lợi ích chung</h3>
<ul><li>Chống mài mòn, chống trầy xước</li><li>Nâng cao giá trị sản phẩm, thu hút khách hàng</li><li>Tăng tính nhận diện thương hiệu</li><li>Có lựa chọn chất liệu thân thiện môi trường</li></ul>', 'Ấn phẩm theo ngành', '/assets/images/thumbs/blog-img2.png', '2025-12-12', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('cach-in-va-quy-uoc-khi-in-bang-cong-nghe-in-flexo', 'Cách in và các quy ước khi in sản phẩm bằng công nghệ in Flexo', 'In Flexo là phương pháp in nổi được dùng rộng rãi trong sản xuất bao bì giấy. Bài viết giải thích quy trình 4 bước, ưu điểm và 5 quy ước bắt buộc phải nắm khi thiết kế file cho in Flexo.', '<p>Công nghệ in Flexo (hay in nổi) là phương pháp in hiện đại được dùng rộng rãi trong ngành sản xuất bao bì giấy và các vật liệu đóng gói khác. Flexo in được trên nhiều chất liệu — giấy, nhựa, vải, phim nhựa — cho kết quả sắc nét và độ bền màu cao.</p>
<h3>Quy trình in Flexo gồm 4 bước</h3>
<ol><li><strong>Chuẩn bị hình ảnh và dữ liệu in.</strong> Thiết kế được chuyển thành file vector để đảm bảo chất lượng sắc nét ở mọi tỉ lệ.</li>
<li><strong>Làm khuôn in (plate making).</strong> Dùng ánh sáng UV để khắc hình ảnh lên bề mặt khuôn. Khuôn làm từ nhựa, cao su hoặc photopolymer.</li>
<li><strong>In lên chất liệu bao bì.</strong> Mực được áp lên khuôn rồi truyền sang chất liệu. Mực Flexo nhanh khô nên chạy được tốc độ cao.</li>
<li><strong>Sấy khô và hoàn thiện.</strong> Sản phẩm được sấy, sau đó cắt, gấp và hoàn thiện theo yêu cầu.</li></ol>
<h3>Lợi ích của in Flexo trong sản xuất bao bì giấy</h3>
<ul><li><strong>Chất lượng cao</strong> — hình ảnh sắc nét, màu sắc tươi sáng</li>
<li><strong>Tốc độ nhanh</strong> — tiết kiệm thời gian sản xuất, giảm chi phí</li>
<li><strong>Đa dạng chất liệu</strong> — in được trên giấy kraft, giấy couche, nhựa và màng phim</li>
<li><strong>Tiết kiệm về dài hạn</strong> — chi phí làm khuôn ban đầu cao nhưng đơn giá giảm mạnh khi sản lượng lớn</li></ul>
<h3>5 quy ước quan trọng khi in Flexo</h3>
<ol><li><strong>Chọn mực in phù hợp chất liệu</strong> để đảm bảo độ bền và độ sắc nét.</li>
<li><strong>Điều chỉnh áp lực in.</strong> Áp lực lệch làm mực lem hoặc in không đủ rõ.</li>
<li><strong>Tối ưu hoá thiết kế.</strong> Chi tiết quá nhỏ hoặc quá phức tạp sẽ mất nét khi in.</li>
<li><strong>Kiểm tra độ dày khuôn in</strong> — khuôn phải đúng độ dày thì hình mới rõ.</li>
<li><strong>Kiểm tra sự đồng nhất màu sắc.</strong> Hệ thống kiểm soát màu phải được hiệu chỉnh để thành phẩm khớp với thiết kế ban đầu.</li></ol>', 'Kiến thức in ấn', '/assets/images/thumbs/blog-img3.png', '2025-11-17', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('mau-thiet-ke-hop-qua-tang-2026', 'Các mẫu thiết kế và phong cách hộp quà tặng mới nhất năm 2026', 'Năm dạng hộp quà đang được chuộng nhất 2026: nắp nam châm, ngăn kéo, gấp gọn, dạng túi xách và hộp in theo yêu cầu — kèm xu hướng màu sắc.', '<h3>1. Hộp quà dạng nắp nam châm</h3>
<p>Thiết kế hiện đại, tinh giản; nắp mở bằng nam châm, dễ đóng mở và giữ cố định chắc chắn. Phù hợp quà cao cấp: rượu, mỹ phẩm, đồng hồ.</p>
<h3>2. Hộp quà dạng trượt (ngăn kéo)</h3>
<p>Thiết kế hai lớp: vỏ ngoài và khay trong, tạo trải nghiệm mở quà độc đáo. Thích hợp cho set bánh, trà, cà phê, phụ kiện.</p>
<h3>3. Hộp quà gấp gọn</h3>
<p>Tiện lợi và thân thiện môi trường. Chất liệu giấy Ivory hoặc Kraft, tái chế được, tiết kiệm chi phí vận chuyển.</p>
<h3>4. Hộp quà dạng túi xách</h3>
<p>Kết hợp hộp quà và túi xách, phù hợp giới trẻ và ngành thời trang, mỹ phẩm.</p>
<h3>5. Hộp quà in ấn theo yêu cầu</h3>
<p>Tuỳ chỉnh thiết kế, logo, màu sắc; gia công cao cấp: ép kim, phủ UV, bế nổi.</p>
<h3>Xu hướng màu sắc 2026</h3>
<ul><li>Pastel và metallic</li><li>Phong cách minimalist</li><li>Hoa văn Á Đông kết hợp hiện đại</li><li>Hiệu ứng in 3D và ép nổi</li></ul>', 'Xu hướng thiết kế', '/assets/images/thumbs/blog-page-img1.png', '2025-11-05', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('kieu-dang-thung-dung-trai-cay', 'Các kiểu dáng thiết kế mới nhất cho thùng đựng trái cây', 'Năm kiểu thùng trái cây phổ biến: hiện đại sang trọng, chuẩn xuất khẩu, quà biếu cao cấp, thân thiện môi trường và thiết kế theo yêu cầu.', '<h3>1. Kiểu hiện đại — sang trọng</h3>
<p>Hộp vuông hoặc chữ nhật cứng cáp với tay cầm chắc chắn, tông màu rực rỡ, hình ảnh trái cây tươi kết hợp in nổi hoặc ép kim. Phù hợp nho, táo, cherry cao cấp.</p>
<h3>2. Chuẩn xuất khẩu</h3>
<p>Giấy carton 3–5 lớp chống ẩm, nắp gập hoặc khoá tự động, thông tin sản phẩm và mã QR rõ nét.</p>
<h3>3. Quà biếu cao cấp</h3>
<p>Nắp mở lật, quai xách dây ruy băng, cửa sổ mica trong suốt; gia công ép kim, dập nổi, phủ UV hoặc cán mờ.</p>
<h3>4. Thân thiện môi trường</h3>
<p>Giấy Kraft tái chế, mực sinh học, thiết kế tối giản với tông nâu – xanh tạo cảm giác gần gũi, tự nhiên.</p>
<h3>5. Thiết kế theo yêu cầu</h3>
<p>Tuỳ chỉnh logo, nhận diện thương hiệu, QR code và mã vạch riêng cho từng nhà vườn hoặc nhà phân phối.</p>', 'Ấn phẩm theo ngành', '/assets/images/thumbs/blog-page-img2.png', '2025-10-17', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('mau-bao-li-xi-2026', 'Những mẫu thiết kế và phong cách mới nhất cho bao lì xì 2026', 'Năm phong cách bao lì xì cho Tết 2026: truyền thống, tối giản hiện đại, eco, nghệ thuật và cá nhân hoá có QR code.', '<p>Bao lì xì không chỉ là vật trao gửi lời chúc may mắn mà còn là một sản phẩm văn hoá — mỹ thuật đầy sáng tạo.</p>
<h3>1. Phong cách truyền thống</h3>
<p>Màu đỏ, vàng, cam; hoạ tiết trống đồng, hoa sen, mai vàng, câu đối Tết. Giữ giá trị truyền thống nhưng thiết kế sắc nét, hiện đại. Phù hợp doanh nghiệp, ngân hàng, tổ chức.</p>
<h3>2. Hiện đại — tối giản, trẻ trung</h3>
<p>Màu pastel nhẹ nhàng; ít chi tiết, dùng typography sáng tạo với lời chúc ngắn gọn. Phù hợp Gen Z và Millennials.</p>
<h3>3. Eco — thân thiện môi trường</h3>
<p>Giấy Kraft tái chế, giấy mỹ thuật thô, tông nâu mộc, in mực đơn giản. Phù hợp doanh nghiệp muốn thể hiện trách nhiệm xã hội.</p>
<h3>4. Nghệ thuật — sáng tạo, cá tính</h3>
<p>Kết hợp tranh vẽ tay, hoạ tiết 3D hoặc hoạt hình; in spot UV, ép kim hologram, dập nổi.</p>
<h3>5. Cá nhân hoá — xu hướng nổi bật nhất 2026</h3>
<p>In logo công ty, slogan, tên riêng hoặc lời chúc cá nhân; gắn QR code liên kết đến fanpage hoặc website, vừa quảng bá vừa tạo dấu ấn.</p>', 'Xu hướng thiết kế', '/assets/images/thumbs/blog-page-img3.png', '2025-10-08', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('in-lich-tet-2026-theo-yeu-cau', 'In lịch Tết 2026 theo yêu cầu — lựa chọn cho doanh nghiệp và cá nhân', 'Bốn dòng lịch Tết được đặt nhiều nhất, quy cách sản xuất và bảng giá tham khảo theo từng loại lịch.', '<p>Mỗi dịp Tết, lịch trở thành món quà quen thuộc nhưng đầy ý nghĩa — vừa mang giá trị văn hoá vừa là công cụ quảng bá thương hiệu suốt cả năm.</p>
<h3>Các dòng lịch được ưa chuộng</h3>
<p><strong>Lịch bloc</strong> — truyền thống, đa dạng kích thước, nội dung phong phú (danh ngôn, tử vi, phong thuỷ, ẩm thực). Phù hợp biếu tặng gia đình, đối tác.</p>
<p><strong>Lịch treo tường</strong> — thiết kế 5, 7 hoặc 13 tờ với hình ảnh thương hiệu, được doanh nghiệp chọn nhiều để quảng bá.</p>
<p><strong>Lịch để bàn</strong> — gọn gàng, tiện lợi cho văn phòng, in kèm logo và slogan công ty.</p>
<p><strong>Lịch sổ tay</strong> — sang trọng, kết hợp lịch và sổ ghi chép, thường được các công ty lớn lựa chọn.</p>
<h3>Bảng giá tham khảo</h3>
<table><thead><tr><th>Loại lịch</th><th>Giá (VNĐ/cuốn)</th><th>Số lượng tối thiểu</th></tr></thead><tbody>
<tr><td>Lịch bloc nhỏ</td><td>15.000 – 30.000</td><td>100 cuốn</td></tr>
<tr><td>Lịch treo tường</td><td>20.000 – 30.000</td><td>100 cuốn</td></tr>
<tr><td>Lịch để bàn</td><td>35.000 – 50.000</td><td>100 cuốn</td></tr>
<tr><td>Lịch sổ tay</td><td>60.000 – 100.000</td><td>100 cuốn</td></tr></tbody></table>
<p><em>Giá có thể thay đổi theo chất liệu, thiết kế và số lượng.</em></p>
<h3>Cam kết</h3>
<ul><li>Thiết kế miễn phí</li><li>In nhanh, giao tận nơi</li><li>Đa dạng chất liệu: Couche, Bristol, Ivory</li><li>Gia công cán mờ/bóng, ép kim, phủ UV</li></ul>', 'Ấn phẩm theo ngành', '/assets/images/thumbs/blog-page-img4.png', '2025-09-23', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('mau-thiet-ke-hop-banh-trung-thu', 'Các mẫu thiết kế và kiểu dáng hộp bánh trung thu', 'Năm hướng thiết kế hộp bánh trung thu: cao cấp, hiện đại tối giản, truyền thống, hộp xanh và hộp sáng tạo.', '<h3>1. Hộp cao cấp — sang trọng, quý phái</h3>
<p>Kiểu dáng: hộp gỗ bọc giấy mỹ thuật, hộp ngăn kéo, hộp nắp nam châm. Tông vàng kim, đỏ đô, xanh ngọc; ép kim logo và hoạ tiết cổ điển. Dành cho doanh nghiệp và quà biếu cao cấp.</p>
<h3>2. Hộp hiện đại — tối giản, thanh lịch</h3>
<p>Kiểu dáng: hộp nắp gập, hộp dạng quyển sách. Màu pastel, trắng kem, xanh dương nhạt với hoạ tiết trăng rằm, mây trời. Ít chi tiết, nhiều khoảng trống để tạo sự tinh tế.</p>
<h3>3. Hộp truyền thống — gắn với văn hoá Việt</h3>
<p>Hộp vuông 4–6 bánh, hộp tròn lấy cảm hứng từ mặt trăng; hình ảnh trống đồng, hoa sen, mái đình kết hợp mạ vàng. Chất liệu giấy Duplex cán mờ, giấy Ivory.</p>
<h3>4. Hộp xanh — thân thiện môi trường</h3>
<p>Hộp giấy Kraft, hộp carton, có thể tái sử dụng làm hộp lưu trữ, kèm túi giấy. Phù hợp doanh nghiệp quan tâm eco-friendly.</p>
<h3>5. Hộp sáng tạo — độc đáo, gây ấn tượng</h3>
<p>Hộp lục giác, hộp trăng khuyết, hộp 3D đa tầng; kết hợp cửa sổ trong suốt hoặc hoạ tiết 3D. Xu hướng thiết kế "đáng chụp ảnh" để khách tự lan toả trên mạng xã hội.</p>', 'Xu hướng thiết kế', '/assets/images/thumbs/blog-details-img.png', '2025-09-11', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('mau-kieu-dang-tag-treo', 'Các mẫu kiểu dáng mới nhất của tag treo — chất liệu, hiệu ứng in và dây treo', 'Tag treo không chỉ là thẻ giá. Tổng hợp kiểu dáng, bảng chất liệu, bảng hiệu ứng in và các loại dây treo đang được dùng nhiều nhất.', '<p>Tag treo (thẻ treo nhãn mác) tiện lợi cho việc theo dõi mã hàng và giá bán, là lựa chọn quen thuộc của các thương hiệu thời trang, mỹ phẩm, thực phẩm, công nghệ, thủ công và quà tặng.</p>
<h3>1. Tag treo hình dáng độc lạ</h3>
<ul><li><strong>Tag oval</strong> — bo góc mềm mại, thanh lịch. Phù hợp thời trang nữ, mỹ phẩm, handmade.</li>
<li><strong>Tag tròn</strong> — nhỏ gọn, dễ thương. Dùng cho quà tặng, tiệm bánh, đồ thủ công, decor.</li>
<li><strong>Tag lục giác / lá / bông hoa / đám mây</strong> — thiết kế theo chủ đề, phù hợp thương hiệu cá tính.</li></ul>
<h3>2. Tag vuông / chữ nhật truyền thống</h3>
<p>Tag dạng đứng phù hợp trình bày thông tin sản phẩm, dễ gắn vào quần áo, giày dép, balo. Tag dạng ngang dễ in logo nổi bật, phù hợp túi giấy và quà tặng.</p>
<h3>3. Hiệu ứng in</h3>
<table><thead><tr><th>Kỹ thuật</th><th>Công dụng</th></tr></thead><tbody>
<tr><td>Ép kim nhiều màu</td><td>Làm nổi bật logo, tạo điểm nhấn cao cấp</td></tr>
<tr><td>Bế nổi / dập nổi</td><td>Tăng hiệu ứng chạm, chuyên nghiệp</td></tr>
<tr><td>Phủ UV định hình</td><td>Tạo độ bóng cục bộ ở phần quan trọng</td></tr>
<tr><td>Cán màng bóng/mờ</td><td>Bảo vệ tag, tăng độ bền</td></tr>
<tr><td>In offset 4 màu</td><td>Màu chuẩn xác, sắc nét</td></tr></tbody></table>
<h3>4. Chất liệu phổ biến</h3>
<table><thead><tr><th>Chất liệu</th><th>Ưu điểm</th><th>Ứng dụng</th></tr></thead><tbody>
<tr><td>Giấy Couche</td><td>In màu tốt, giá rẻ, dễ gia công</td><td>Quần áo phổ thông, tag khuyến mãi</td></tr>
<tr><td>Giấy Kraft</td><td>Vintage, thân thiện môi trường</td><td>Handmade, thời trang eco</td></tr>
<tr><td>Giấy Ivory</td><td>Bề mặt mịn, trắng sáng, in đẹp</td><td>Mỹ phẩm, thương hiệu cao cấp</td></tr>
<tr><td>Giấy Bristol</td><td>Định lượng cao, cứng cáp</td><td>Giày dép, balo, tag lớn</td></tr>
<tr><td>Giấy mỹ thuật</td><td>Có vân, ánh kim, texture riêng</td><td>Tag quà tặng, bộ sưu tập</td></tr></tbody></table>
<h3>5. Các loại dây treo</h3>
<table><thead><tr><th>Loại dây</th><th>Phong cách</th></tr></thead><tbody>
<tr><td>Dây chỉ dù</td><td>Sang trọng, bền chắc — thời trang cao cấp</td></tr>
<tr><td>Dây cotton xoắn</td><td>Tự nhiên — handmade / vintage</td></tr>
<tr><td>Dây nhựa bấm sẵn</td><td>Nhanh, tiện — bán lẻ quần áo</td></tr>
<tr><td>Dây kraft bản giấy</td><td>Thân thiện môi trường, dễ tái chế</td></tr></tbody></table>', 'Ấn phẩm theo ngành', '/assets/images/thumbs/blog-new-img1.png', '2025-08-19', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('mau-thiet-ke-bo-lich-de-ban-2026', 'Những mẫu thiết kế mới cho bộ lịch để bàn 2026 — màu sắc và bố cục', 'Xu hướng thiết kế lịch để bàn 2026: tối giản nhưng ấn tượng, bảng màu gợi ý và quy cách sản xuất chuẩn.', '<h3>Xu hướng thiết kế 2026</h3>
<ul><li>Tối giản nhưng ấn tượng: font chữ thanh thoát, bảng màu tinh tế</li>
<li>Nhấn mạnh bản sắc thương hiệu, tuỳ chỉnh theo ngành nghề</li>
<li>Gắn với thông điệp sống bền vững, thân thiện môi trường</li>
<li>Kết hợp hiệu ứng in hiện đại như phủ UV, ép kim</li></ul>
<h3>Gợi ý màu sắc</h3>
<ul><li><strong>Xanh navy</strong> — lịch sự, chuyên nghiệp</li>
<li><strong>Cam đất</strong> — ấm áp, phù hợp sản phẩm thủ công</li>
<li><strong>Be nhạt</strong> — tối giản, dễ phối</li>
<li><strong>Xanh lá sage</strong> — đại diện môi trường, bền vững</li>
<li><strong>Tím pastel</strong> — sáng tạo, nữ tính</li></ul>
<h3>Bố cục phổ biến</h3>
<ul><li>1 tháng / 1 tờ (truyền thống)</li><li>2 tháng / 1 tờ (tiết kiệm giấy)</li><li>Sáng tạo theo chủ đề mùa</li></ul>
<h3>Quy cách sản xuất</h3>
<ul><li>Kích thước: 20 × 15 cm hoặc 21 × 14.5 cm</li>
<li>Giấy Couche 210–250gsm</li>
<li>In offset 4 màu CMYK</li>
<li>Gia công: cán màng, khoét lỗ lò xo, ép kim</li></ul>', 'Xu hướng thiết kế', '/assets/images/thumbs/blog-new-img2.png', '2025-08-04', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('quy-cach-thiet-ke-va-san-xuat-tui-xach-giay', 'Các quy cách phổ biến nhất để thiết kế và sản xuất túi xách giấy', 'Kích thước chuẩn, loại giấy, kỹ thuật in và các loại quai — toàn bộ quy cách cần chốt trước khi đặt sản xuất túi xách giấy cho thương hiệu.', '<h3>1. Kích thước chuẩn theo ngành hàng</h3>
<ul><li>Túi nhỏ (trang sức): 13 × 6 × 18 cm</li>
<li>Túi trung (mỹ phẩm): 20 × 8 × 25 cm</li>
<li>Túi lớn (thời trang): 30 × 10 × 40 cm đến 35 × 12 × 45 cm</li></ul>
<h3>2. Loại giấy</h3>
<ul><li><strong>Giấy Couche</strong> — bề mặt bóng, phù hợp quà tặng đơn giản</li>
<li><strong>Giấy Kraft</strong> — màu nâu, phong cách tự nhiên / vintage</li>
<li><strong>Giấy Ivory</strong> — cứng cáp, phù hợp sản phẩm cao cấp</li>
<li><strong>Giấy Bristol</strong> — dày, trắng sáng</li></ul>
<p>Định lượng phổ biến: <strong>200–350gsm</strong>.</p>
<h3>3. Kỹ thuật in và gia công</h3>
<p>In offset cho màu chuẩn, sắc nét và tối ưu chi phí khi in số lượng lớn. Gia công thường dùng: cán màng bóng/mờ, ép kim, bế nổi, dập chìm, gắn quai.</p>
<h3>4. Các loại quai</h3>
<ul><li>Quai giấy xoắn — thân thiện môi trường</li>
<li>Quai dây dù — bền, sang trọng</li>
<li>Quai ruy băng — mềm mại</li>
<li>Quai PP dẹt — giá tốt</li></ul>
<h3>5. Lưu ý khi thiết kế</h3>
<ul><li>Logo rõ ràng, không đặt sát mép gấp</li>
<li>Chọn định lượng giấy phù hợp trọng lượng sản phẩm</li>
<li>Đặt từ 300–500 túi để tối ưu chi phí in offset</li></ul>', 'Ấn phẩm theo ngành', '/assets/images/thumbs/blog-new-img3.png', '2025-07-31', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('meo-va-luu-y-khi-san-xuat-thung-carton', 'Các mẹo và điều cần lưu ý khi sản xuất thùng carton', 'Thùng carton bồi Duplex không chỉ bảo vệ sản phẩm mà còn là công cụ xây dựng thương hiệu. Cách chọn sóng carton, quy ước thiết kế và những lỗi hay gặp khi đặt sản xuất.', '<p>Thùng carton cao cấp bồi giấy Duplex, in offset và cán màng bóng/mờ ngày nay không chỉ là vật liệu bảo vệ sản phẩm — nó là một phần của nhận diện thương hiệu, thứ khách hàng nhìn thấy đầu tiên khi nhận hàng.</p>
<h3>1. Hiểu đúng về cấu tạo thùng carton bồi Duplex</h3>
<p>Đây là loại thùng cấu tạo từ lớp sóng carton bên trong và lớp giấy Duplex bên ngoài. Ưu điểm: cứng cáp nhờ carton sóng, bề mặt in sắc nét thẩm mỹ cao, bảo vệ sản phẩm tốt.</p>
<h3>2. Chọn đúng sóng carton</h3>
<ul><li><strong>Sóng E</strong> — sóng nhỏ, mịn, định hình tốt. Dùng cho thùng mỹ phẩm, hàng nhẹ.</li>
<li><strong>Sóng B</strong> — sóng cao hơn, chịu lực tốt. Dùng cho thực phẩm, linh kiện.</li>
<li><strong>Sóng E-VX</strong> — tổ hợp tăng cường độ cứng. Dùng cho hàng cao cấp, hàng xuất khẩu.</li></ul>
<h3>3. Quy ước thiết kế bắt buộc</h3>
<ul><li>Biên dán tối thiểu <strong>25mm</strong> để thùng không bị bung</li>
<li>Nếp gấp phải được tạo rãnh chuẩn</li>
<li>Kích thước nên dư <strong>0.5–1cm</strong> so với sản phẩm để dễ đóng gói</li></ul>
<h3>4. Quy cách và thông số kỹ thuật tham khảo</h3>
<table><thead><tr><th>Tiêu chí</th><th>Thông số</th></tr></thead><tbody>
<tr><td>Giấy bồi</td><td>Duplex 250–350gsm</td></tr>
<tr><td>Lớp sóng</td><td>Carton sóng B, C hoặc BE</td></tr>
<tr><td>Kỹ thuật in</td><td>In offset 4 màu CMYK</td></tr>
<tr><td>Gia công</td><td>Cán màng bóng/mờ, ép kim, bế nổi</td></tr>
<tr><td>Gấp dán</td><td>Keo tự động hoặc dán tay</td></tr></tbody></table>
<h3>5. Những lỗi hay gặp</h3>
<ul><li>Màu in lệch nhẹ giữa giấy thường và giấy cán màng — luôn duyệt test proof trước</li>
<li>Thiết kế quá nhiều nếp gấp nhỏ</li>
<li>Lạm dụng nhiều hiệu ứng cùng lúc: chi phí cao và dễ nứt bề mặt</li>
<li>Thiếu phối hợp giữa khâu thiết kế, in ấn và gia công</li></ul>', 'Bạn cần biết', '/assets/images/thumbs/blog-img1.png', '2025-07-31', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('cac-loai-giay-pho-bien-de-lam-namecard', 'Các loại giấy phổ biến để làm namecard (danh thiếp)', 'Couche, Bristol, Ivory hay giấy mỹ thuật — mỗi loại giấy làm danh thiếp có ưu nhược điểm riêng. Kèm bảng quy cách in namecard chất lượng cao.', '<p>Danh thiếp là công cụ đại diện cho hình ảnh cá nhân hoặc doanh nghiệp trong các cuộc gặp chuyên nghiệp. Chọn đúng chất liệu giấy nâng giá trị thương hiệu và thể hiện tính chuyên nghiệp ngay từ cái chạm đầu tiên.</p>
<h3>1. Giấy Couche — phổ biến và tiết kiệm</h3>
<p><strong>Ưu điểm:</strong> bề mặt bóng mịn, in màu chuẩn và đẹp, giá thành rẻ.<br><strong>Nhược điểm:</strong> ít cao cấp, dễ gãy nếp nếu không cán màng.<br><strong>Dùng cho:</strong> namecard phổ thông, nhân viên, startup.</p>
<h3>2. Giấy Bristol — độ cứng tốt</h3>
<p><strong>Ưu điểm:</strong> dày dặn, cứng cáp, dễ in offset, phù hợp nhiều kiểu xử lý bề mặt.<br><strong>Nhược điểm:</strong> không có độ bóng sẵn, cần cán màng.<br><strong>Dùng cho:</strong> namecard công ty, phòng ban, ngành dịch vụ.</p>
<h3>3. Giấy Ivory</h3>
<p><strong>Ưu điểm:</strong> chất lượng in tốt, màu sắc sắc nét, cảm giác cầm sang trọng.<br><strong>Dùng cho:</strong> danh thiếp giám đốc, namecard thương hiệu cao cấp.</p>
<h3>4. Giấy mỹ thuật — sang trọng</h3>
<p><strong>Ưu điểm:</strong> đa dạng màu sắc và hiệu ứng bề mặt, dễ kết hợp ép kim, dập chìm, phủ UV.<br><strong>Nhược điểm:</strong> giá cao hơn, một số loại in màu không chuẩn như giấy trơn.<br><strong>Dùng cho:</strong> danh thiếp nghệ thuật, namecard cá nhân sáng tạo, thương hiệu cao cấp.</p>
<h3>Quy cách in namecard chất lượng cao</h3>
<table><thead><tr><th>Tiêu chí</th><th>Thông số đề xuất</th></tr></thead><tbody>
<tr><td>Kích thước</td><td>9 × 5.5 cm hoặc 8.8 × 5.3 cm</td></tr>
<tr><td>Định lượng giấy</td><td>250gsm – 400gsm</td></tr>
<tr><td>Gia công bề mặt</td><td>Cán mờ, cán bóng, ép kim, phủ UV, dập nổi</td></tr>
<tr><td>Kỹ thuật in</td><td>In offset, in kỹ thuật số chất lượng cao</td></tr>
<tr><td>Số lượng tối thiểu</td><td>100 – 500 cái</td></tr></tbody></table>', 'Ấn phẩm theo ngành', '/assets/images/thumbs/blog-img2.png', '2025-07-26', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('meo-thiet-ke-hop-banh', 'Các mẹo thiết kế hộp bánh thu hút khách hàng, tăng doanh số', 'Hộp bánh ngày nay là công cụ marketing trực tiếp. Năm mẹo thiết kế từ trải nghiệm mở hộp đến đồng bộ nhận diện thương hiệu.', '<p>Hộp bánh không đơn thuần là lớp vỏ bảo vệ — nó là công cụ marketing trực tiếp, tạo ấn tượng ngay khi khách cầm trên tay.</p>
<h3>1. Trải nghiệm mở hộp (unboxing)</h3>
<p>Thiết kế hộp ngăn kéo, gập cạnh hoặc nắp bật nam châm; thêm lời nhắn ngắn hoặc chữ viết tay in giả để tạo cảm giác cá nhân.</p>
<h3>2. Màu sắc và hình ảnh</h3>
<p>Dùng tông pastel, trắng kem, nâu nhạt; ảnh bánh thật hoặc minh hoạ 3D; áp dụng phủ UV định hình và ép kim để tạo chiều sâu.</p>
<h3>3. Chất liệu và kiểu dáng theo phân khúc</h3>
<ul><li>Cao cấp: giấy Ivory hoặc giấy mỹ thuật</li><li>Trung cấp: giấy Duplex</li><li>Bình dân: giấy Kraft</li></ul>
<p>Kiểu hộp: nắp rời, gập nắp chéo, hình tròn hoặc tam giác.</p>
<h3>4. Yếu tố bền vững</h3>
<p>Dùng giấy tái chế, thêm icon "ECO" hoặc "100% recyclable" để tạo niềm tin.</p>
<h3>5. Nhận diện thương hiệu</h3>
<p>Logo ở vị trí dễ nhìn, thêm slogan và QR code, đồng bộ hoá giữa hộp, sticker, tag và túi xách.</p>', 'Xu hướng thiết kế', '/assets/images/thumbs/blog-img3.png', '2025-07-22', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('kieu-dang-va-chat-lieu-lam-hop-giay-giay', 'Những kiểu dáng phổ biến và chất liệu phù hợp để làm hộp giày giấy', 'Hộp âm dương, hộp ngăn kéo hay hộp gấp gọn? So sánh ba kiểu dáng hộp giày phổ biến và ba loại giấy tương ứng với từng phân khúc sản phẩm.', '<h3>Các kiểu dáng hộp giày phổ biến</h3>
<p><strong>1. Hộp giày nắp rời (hộp âm dương)</strong> — thiết kế truyền thống với hai phần riêng biệt. Dễ đóng mở, bảo vệ cứng cáp, phù hợp mọi loại giày.</p>
<p><strong>2. Hộp giày kiểu ngăn kéo (hộp trượt)</strong> — thiết kế hiện đại, kéo trượt tinh tế. Sang trọng, bảo vệ tối ưu, dùng cho giày cao cấp.</p>
<p><strong>3. Hộp giày gấp gọn (hộp xếp)</strong> — xếp gọn được, tiết kiệm không gian, giảm chi phí lưu kho.</p>
<h3>Chất liệu giấy</h3>
<table><thead><tr><th>Chất liệu</th><th>Đặc điểm</th><th>Ứng dụng</th></tr></thead><tbody>
<tr><td>Giấy Duplex</td><td>Cứng cáp, giá tốt, dễ in</td><td>Hộp giày phổ thông</td></tr>
<tr><td>Giấy Kraft</td><td>Thân thiện môi trường, vintage</td><td>Giày thời trang, sneaker</td></tr>
<tr><td>Giấy Ivory</td><td>Cao cấp, in sắc nét</td><td>Giày luxury</td></tr></tbody></table>
<h3>Tiêu chuẩn chất lượng</h3>
<ul><li>Định lượng giấy: 250–350gsm</li>
<li>Kích thước phổ biến: 24×14×9 cm (nhỏ), 30×18×10 cm (trung), 34×20×12 cm (lớn)</li>
<li>Xử lý bề mặt: cán màng, ép kim, phủ UV</li>
<li>In ấn: offset để đảm bảo độ bền màu</li></ul>', 'Bạn cần biết', '/assets/images/thumbs/blog-page-img1.png', '2025-07-15', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('thung-carton-2025-xu-huong-va-doi-moi', 'Thùng carton: xu hướng và đổi mới trong ngành in ấn', 'Thùng carton không còn chỉ là phương tiện đóng gói mà đã thành một phần của chiến lược marketing và cam kết môi trường của thương hiệu.', '<p>Thùng carton ngày nay không chỉ là phương tiện đóng gói mà còn là một phần quan trọng trong chiến lược marketing và bảo vệ môi trường của doanh nghiệp.</p>
<h3>1. Tính bền vững</h3>
<ul><li>Sử dụng nguyên liệu tái chế</li><li>Quy trình sản xuất thân thiện môi trường</li><li>Giảm thiểu lượng rác thải</li></ul>
<h3>2. Thiết kế sáng tạo và tuỳ biến</h3>
<ul><li>In nhiều màu sắc và hình ảnh sắc nét</li><li>Mẫu thùng độc đáo, dễ tuỳ biến theo thương hiệu</li><li>Truyền tải thông điệp mạnh mẽ ngay trên bao bì</li></ul>
<h3>3. Tích hợp trải nghiệm khách hàng</h3>
<ul><li>Thiết kế bên trong sáng tạo</li><li>Thông điệp cá nhân hoá</li><li>Tạo ấn tượng tốt ở khoảnh khắc mở thùng</li></ul>
<h3>4. Tăng cường an toàn và bảo vệ</h3>
<ul><li>Chống va đập và chống thấm nước</li><li>Cải thiện độ bền</li><li>Đảm bảo hàng hoá đến tay người tiêu dùng an toàn</li></ul>', 'Bạn cần biết', '/assets/images/thumbs/blog-page-img2.png', '2025-03-03', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('ngay-hoi-nguoi-binh-dinh-lan-9-2025', 'In Ấn Thời Đại đồng hành cùng Ngày hội Người Bình Định lần 9 năm 2025', 'Sự kiện quy tụ người con quê hương Bình Định tại TP.HCM với gian hàng ẩm thực, văn nghệ truyền thống và hoạt động thể thao.', '<p>Công ty In Ấn Thời Đại đồng hành cùng Ngày hội Người Bình Định lần 9 năm 2025 tại TP. Hồ Chí Minh. Sự kiện quy tụ người con quê hương Bình Định với các hoạt động đa dạng: gian hàng ẩm thực, tiết mục văn nghệ truyền thống và hoạt động thể thao.</p>
<p>Tham gia sự kiện là cơ hội để gặp gỡ bạn bè, tìm hiểu về văn hoá địa phương và để các doanh nghiệp kết nối hợp tác.</p>', 'Hoạt động - Sự kiện', '/assets/images/thumbs/blog-page-img3.png', '2025-02-25', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('year-end-party-2024', 'Year End Party 2024 — Kết nối và toả sáng cùng Thời Đại', 'Nhìn lại một năm 2024 nhiều biến động của ngành in ấn và ba định hướng lớn cho năm 2025.', '<p>Công ty In Ấn Thời Đại tổ chức tiệc cuối năm 2024 để nhìn lại những thành tựu đạt được và chào đón năm mới với nhiều cơ hội cùng thách thức.</p>
<p>Năm 2024, ngành in ấn đối mặt với nhiều thách thức từ biến động thị trường đến thay đổi nhu cầu khách hàng. Nhờ nỗ lực không ngừng của toàn thể nhân viên, công ty đã vượt qua khó khăn và đạt được nhiều thành tựu.</p>
<h3>Định hướng 2025</h3>
<ul><li>Mở rộng thị trường để gia tăng hiện diện thương hiệu</li>
<li>Đổi mới sáng tạo và phát triển sản phẩm mới</li>
<li>Đầu tư đào tạo nhân lực để nâng cao kỹ năng và năng lực</li></ul>
<h3>Chương trình</h3>
<ul><li>Check-in ảnh kỷ niệm năm 2024</li><li>Họp cuối năm nhìn lại khó khăn và định hướng 2025</li><li>Tiệc trưa gặp gỡ và xây dựng mối quan hệ</li><li>Giao lưu, tặng quà cho cá nhân và tập thể xuất sắc</li></ul>', 'Hoạt động - Sự kiện', '/assets/images/thumbs/blog-page-img4.png', '2025-01-20', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
insert into public.posts (slug, title, excerpt, content, category, cover_image_url, published_at, author) values ('ky-niem-15-nam-va-team-building-phan-thiet', 'Kỷ niệm 15 năm thành lập: hành trình phát triển và team building tại Phan Thiết', 'Ngày 9/7/2024 đánh dấu 15 năm kể từ ngày thành lập công ty, được kỷ niệm bằng một chương trình team building tại Phan Thiết.', '<p>Công ty kỷ niệm một cột mốc quan trọng vào ngày 9/7/2024, đánh dấu 15 năm hoạt động kể từ ngày thành lập 9/7/2009, bằng một chương trình team building tại Phan Thiết.</p>
<p>Hành trình bắt đầu từ những bước đi nhỏ nhưng đầy quyết tâm với mục tiêu cung cấp sản phẩm in ấn chất lượng. Qua 15 năm, In Ấn Thời Đại đã mở rộng quy mô, tiếp nhận các dự án lớn, xây dựng đội ngũ chuyên nghiệp và đầu tư công nghệ hiện đại để nâng cao chất lượng sản phẩm, dịch vụ.</p>
<p>Chương trình tại Phan Thiết không chỉ là dịp kỷ niệm mà còn là cơ hội để nhân viên nhìn lại chặng đường đã qua và gắn kết với nhau qua các trò chơi đồng đội.</p>
<p>Công ty gửi lời cảm ơn đến khách hàng, đối tác và toàn thể nhân viên, cam kết tiếp tục cung cấp dịch vụ chất lượng cao.</p>', 'Hoạt động - Sự kiện', '/assets/images/thumbs/blog-details-img.png', '2024-07-10', 'In Ấn Thời Đại')
  on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, category = excluded.category, cover_image_url = excluded.cover_image_url, published_at = excluded.published_at, author = excluded.author;
